### ISSUE TITLE
Add support for three-way relationships

### ISSUE THREAD

**Issue by watsonbox** [domurtag/iou#2]
Can I use IOU to track expenses between three involved parties?  Say, Ann, Bob, and Jane?

**Comment by domurtag** [comment]
Great idea, assign yourself as owner of this issue and send me a PR

**Comment by domurtag** [comment]
Yes

**Comment by domurtag** [comment]
Terribly sorry, but here at IOU HQ we're firm believers in the sanctity of monogamous relationships. If it's a ménage à trois you're after, you'll have to look elsewhere.

**Comment by watsonbox** [comment]
Hi there. Is it true that there's recently been a sharp uptick in development resource at Murtaghsoft and that we may finally see issues like this one revived?
